name: projex_app
description: A fullstack project tracking application but with flutter.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_riverpod: ^2.3.0
  flutter_hooks: ^0.18.4
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  go_router: ^6.2.0
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  flutterfire_ui: ^0.4.1
  firebase_auth: ^4.2.9
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.2
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
    version: any
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  intl: ^0.17.0
  uuid: ^3.0.6
  percent_indicator: ^4.2.2
  animate_do: ^3.0.2
  badges: ^3.0.2
  animated_bottom_navigation_bar: ^1.1.0+1
  bubble: ^1.2.1
  cloud_functions: ^4.0.11
  hooks_riverpod: ^2.3.0
  transparent_image: ^2.0.0
  slang: ^3.13.0
  slang_flutter: ^3.13.0
  stack_trace: ^1.11.0
  file_picker: ^5.2.5
  firebase_storage: ^11.0.14
  photo_view: ^0.14.0
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.10
  slang_build_runner: ^3.13.0
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/env.dat
