name: projex_app
description: A fullstack project tracking application but with flutter.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  flutter_hooks: ^0.18.3
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
  go_router: ^3.0.7
  cloud_firestore: ^3.1.13
  firebase_core: ^1.15.0
  firebase_messaging: ^11.2.14
  flutterfire_ui: ^0.4.0+3
  firebase_auth: ^3.3.15
  firebase_storage: ^10.2.15
  flutter_dotenv: ^5.0.2
  google_sign_in: ^5.3.0
  flutter_screenutil: ^5.4.0+1
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  path: ^1.8.0
  form_builder: ^1.0.1
  form_builder_image_picker: ^2.0.0
  form_builder_validators: ^8.1.1
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  fast_i18n: ^5.12.3
  flutter_lints: ^1.0.0
  freezed: ^2.0.2
  build_runner: ^2.1.10
  json_serializable: ^6.1.6


flutter:
  uses-material-design: true
  assets:
    - assets/env.dat
